server:
  tomcat:
    uri-encoding: UTF-16

spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb
#      max-file-size: 500Mb
#      max-request-size: 100Mb

management:
  security:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  max:
    host:
      connections: 32
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 60000
#  routes:
#    resource:
#path: /ws/**
#                   serviceId: btbs-user-service
