management:  #actuator
  endpoints:
    web:
      exposure:
        include: "*"  #打开全部请求端点

---
spring:
  profiles: 8021

server:
  port: 8021

management:
  server:
    port: 8027

---
spring:
  profiles: 8022

server:
  port: 8022

management:
  server:
    port: 8028