management:  #actuator
  endpoints:
    web:
      exposure:
        include: "*"  #打开全部请求端点

---
spring:
  profiles: single

server:
  port: 8021

management:
  server:
    port: 8027

---
spring:
  profiles: ha-8022

  server:
    port: 8022

management:
  server:
    port: 8028

---
spring:
  profiles: ha-8023

server:
  port: 8021

management:
  server:
    port: 8029